version: '3'
services:
  mlflow:
    build:
      context: .
      dockerfile: mlflow.Dockerfile
    image: tryfonrdnestle/mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./workspace:/mlflow/artifacts
